(************************************************************
 * WARNING!
 *
 * This file is generated by ocamlrpcgen from the source file
 * test.x
 *
 ************************************************************)

(* Type definitions *)

type x = 
     { 
       mutable x_a : Netnumber.int4;
       mutable x_b : Netnumber.int8;
     }
and e = 
     Netnumber.int4
and u = 
     [ | `oNe of (Netnumber.int4) | `Two of (Netnumber.int8) ]
and e2 = 
     Netnumber.int4
and u2 = 
     [ | `one_ of (Netnumber.int4) | `two_ of (Netnumber.int8) ]
and y = 
     ( Netnumber.int4 * Netnumber.int8 )
;;
exception X_x of x
exception X_e of e
exception X_u of u
exception X_e2 of e2
exception X_u2 of u2
exception X_y of y
;;

(* Constant definitions *)

val enum_one : Netnumber.int4;;
val enum_two : Netnumber.int4;;
val one_ : Netnumber.int4;;
val two_ : Netnumber.int4;;

(* Conversion functions *)

val _to_x : Xdr.xdr_value -> x;;
val _of_x : x -> Xdr.xdr_value;;
val _to_e : Xdr.xdr_value -> e;;
val _of_e : e -> Xdr.xdr_value;;
val _to_u : Xdr.xdr_value -> u;;
val _of_u : u -> Xdr.xdr_value;;
val _to_e2 : Xdr.xdr_value -> e2;;
val _of_e2 : e2 -> Xdr.xdr_value;;
val _to_u2 : Xdr.xdr_value -> u2;;
val _of_u2 : u2 -> Xdr.xdr_value;;
val _to_y : Xdr.xdr_value -> y;;
val _of_y : y -> Xdr.xdr_value;;

(* XDR definitions *)

val xdrt_x : Xdr.xdr_type_term;;
val xdrt_e : Xdr.xdr_type_term;;
val xdrt_u : Xdr.xdr_type_term;;
val xdrt_e2 : Xdr.xdr_type_term;;
val xdrt_u2 : Xdr.xdr_type_term;;
val xdrt_y : Xdr.xdr_type_term;;

(* Program definitions *)


